language: go
os: linux
go_import_path: cirello.io/pglock
go:
  - "1.16"

env:
  - GO111MODULE=on

services:
  - docker

before_install:
  - go get github.com/mattn/goveralls
  - docker run -d --name pg13 -e POSTGRES_PASSWORD=mysecretpassword -p 5413:5432 postgres:13

install: true

script:
  - docker ps -a
  - docker logs pg13
  - go test -mod=mod -race                                      -v ./... -dsn=postgres://postgres:mysecretpassword@localhost:5413/postgres?sslmode=disable
  - go test -mod=mod -covermode=count -coverprofile=profile.cov -v ./... -dsn=postgres://postgres:mysecretpassword@localhost:5413/postgres?sslmode=disable
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
  - go test -mod=mod                                               ./... -dsn=postgres://postgres:mysecretpassword@localhost:5413/postgres?sslmode=disable -count=50 -run=TestStress
